In [1]:
#1.	Write a Python Program to Add Two Matrices?

In [16]:
import numpy as np

a=np.array([[1,2,3],[3,4,5]])
b=np.array([[3,4,5],[2,4,7]])
c=np.add(a,b)
print("Addition of two matrices:", c)

Addition of two matrices: [[ 4  6  8]
 [ 5  8 12]]


In [15]:
#2.	Write a Python Program to Multiply Two Matrices?

In [26]:
import numpy as np

a=np.array([[2,3,3],[3,2,4]])
b=np.array([[3,5],[2,3],[2,3]])
c=a.dot(b)
print("Multiplication of two arrays are :",c)

Multiplication of two arrays are : [[18 28]
 [21 33]]


In [27]:
#3.	Write a Python Program to Transpose a Matrix?

In [30]:
import numpy as np

a=np.array([[1,2,3],[3,4,5]])
print(a.transpose())


[[1 3]
 [2 4]
 [3 5]]


In [31]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [32]:
#4.	Write a Python Program to Sort Words in Alphabetic Order?

In [42]:
a=(input("Enter a string: "))

b=a.split()

b.sort()


for i in b:
    print(i)

Enter a string: hi hello thank you
hello
hi
thank
you


In [43]:
#5.	Write a Python Program to Remove Punctuation From a String?

In [57]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

a = "HI!!! HELLO[][][]() THANK YOU...."

b= ""
for char in a:
    if char not in punctuations:
        b = b + char

print(b)


HI HELLO THANK YOU
